# Generated by Django 5.0.1 on 2024-02-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0002_iteminfo_alter_items_name_delete_itemimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="money_spent",
            field=models.IntegerField(null=True),
        ),
    ]
