# Generated by Django 5.0.1 on 2024-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0004_alter_amount_extra_amount_last_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="iteminfo",
            name="item_name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
