# Generated by Django 5.0.1 on 2024-02-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0005_alter_iteminfo_item_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="management.iteminfo"
            ),
        ),
    ]
