# Generated by Django 5.0.1 on 2024-02-01 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0006_alter_items_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="management.iteminfo"
            ),
        ),
    ]
