# Generated by Django 5.0.1 on 2024-02-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0007_alter_items_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="month",
            name="money_spent",
            field=models.IntegerField(default=0),
        ),
    ]
